### ISSUE TITLE
Yahoo API - JSON parsing - Error&Fix

### ISSUE THREAD

**Issue by 1ultimat3** [fho/stockanalyser#1]
Thanks for the great project. I also wanted to implement and tune the Levermann-Strategy, but why reinventing the wheel :)  

I get the following error

```

TypeError: the JSON object must be str, not 'bytes'  /usr/lib/python3.5/json/__init__.py:312: TypeError
```

**This can be fixed in line #34 in yahoo.py by decoding to utf-8:**
```
res = json.loads(resp.decode("utf-8"))
```

**Comment by fho** [comment]
In the current state the software works for me, I added all DAX stocks, update the rating every week and and tests the decisions with a stock simulation game.
But sometimes errors occur and I'm currently only doing quick fixes.
There are a lot of things to add and improve .

I would be happy about your pull requests :)

The error didn't happened with python3.6 for me, I added your fix.

thanks a lot!

**Comment by 1ultimat3** [comment]
cool, I will fork&request pull requests in the future
